version: '3.9'

services:
  python-iot-app:
    build: .
    container_name: python-iot-container
    ports:
      - "8001:8000"
    environment:
      - STARTUP_DELAY=15                        # Wartezeit vor System-Start (Sekunden)
      - AUTO_GENERATOR_INITIAL_DELAY=15        # Wartezeit vor erstem Auto-Fehler (Sekunden)  
      - AUTO_GENERATOR_INTERVAL=60             # Intervall zwischen Auto-Fehlern (Sekunden)
      - ENABLE_AUTO_GENERATOR=true             # Auto-Generator aktivieren
      - ANYTHINGLLM_URL=http://172.18.0.1:3001  # ← Gateway des anythingllm-Netzwerks
      - ANYTHINGLLM_API_KEY=KE7053N-30JM5PZ-KAPMXDP-KXJQC3N
      - MQTT_BROKER=localhost
      - PYTHONUNBUFFERED=1
      - ENABLE_MQTT=false
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
