version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_stack
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-models:/root/.ollama

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"
    volumes:
      - ./openwebui-data:/app/backend/data
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    depends_on:
      - ollama

  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    container_name: middleware
    ports:
      - "8080:8080"
    depends_on:
      - ollama
