version: '3.9'

services:
  python-iot-app:
    build: .
    container_name: python-iot-container
    ports:
      - "8000:8000"
    environment:
      - ANYTHINGLLM_URL=http://host.docker.internal:3001
      - ANYTHINGLLM_API_KEY=KE7053N-30JM5PZ-KAPMXDP-KXJQC3N
      - MQTT_BROKER=localhost
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge

volumes:
  data:
  logs: