version: '3.9'

services:
  python-iot-app:
    build: 
    container_name: python-iot-container
    context: https://github.com/prusaluy07/iot-projekt.git#main
    ports:
      - "8001:8000"
    environment:
      - ANYTHINGLLM_TIMEOUT=30      # Timeout pro Versuch (Sekunden)
      - ANYTHINGLLM_RETRIES=30       # Anzahl Wiederholungsversuche
      - STARTUP_DELAY=5                        # Wartezeit vor System-Start (Sekunden)
      - AUTO_GENERATOR_INITIAL_DELAY=10        # Wartezeit vor erstem Auto-Fehler (Sekunden)  
      - AUTO_GENERATOR_INTERVAL=59             # Intervall zwischen Auto-Fehlern (Sekunden)
      - ENABLE_AUTO_GENERATOR=true             # Auto-Generator aktivieren
      - ANYTHINGLLM_URL=http://172.20.0.3:3001  # ← Gateway des anythingllm-Netzwerks
      - ANYTHINGLLM_API_KEY=KE7053N-30JM5PZ-KAPMXDP-KXJQC3N
      - MQTT_BROKER=localhost
      - PYTHONUNBUFFERED=1
      - ENABLE_MQTT=false
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
