version: '3.9'

services:
  python-iot-app:
    build: .
    container_name: python-iot-container
    ports:
      - "8001:8000"  # Port 8001 extern, 8000 intern
    environment:
      - ANYTHINGLLM_URL=http://172.17.0.2:3001
      - ANYTHINGLLM_API_KEY=KE7053N-30JM5PZ-KAPMXDP-KXJQC3N
      - MQTT_BROKER=localhost
      - PYTHONUNBUFFERED=1
      - ENABLE_MQTT=false
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
