version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - /docker/ollama:/root/.ollama   # Modelle + Config direkt auf /docker
    restart: always

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    volumes:
      - /docker/openwebui:/app/backend/data   # persistent auf /docker
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    depends_on:
      - ollama
    restart: always

  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /docker/middleware:/app   # Code + Daten persistent auf /docker
    depends_on:
      - ollama
    restart: always
